spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-54-86-106-48.compute-1.amazonaws.com/d7rvfnsvj9bjbe
  username: knlqcupmedvkzd
  password: 314f33bf88cbf18e2beb7531f2a930804f36b8e9cb2d63c3c433be7a695f7cd8
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  token.expired-time-ms: 2592000000